[package]
name = "minecraft-native-helper"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
[dependencies]
xodus = { path = "vendor/xodus/crates/xodus" }
tokio = { version = "1.53.1", features = ["full"] }
reqwest = { version = "0.13.4", features = ["json", "stream"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
futures-util = "0.3.34"
tao = "0.37.0"
wry = "0.56.1"
uuid = "1.25.0"

credential-bridge = { path = "../Shared/CredentialBridge" }
msixvc = { path = "vendor/xodus/crates/msixvc" }
sha2 = "0.10"
base64 = "0.22"
zip = { version = "2.4", default-features = false, features = ["deflate"] }
msi = "0.8"
cab = "0.6"
keyring-core = "1.0"
sha1 = "0.10"

bedrock-account-service = { package = "minecraft-bedrock-account-service", path = "../Compatibility/Bedrock/AccountService" }

[features]
bootstrap-pins = []

[patch.crates-io]
ntfs = { git = "https://github.com/xodus-gaming/ntfs.git", rev = "5edc794c3ec73a2722dad24abefd05f270d3e066" }
